export const ROLES = {
  ADMIN: 'ADMIN',
  USER: 'USER'
};

export const CHECKIN_STATUS = {
  PRESENT: 'PRESENT',
  REJECTED: 'REJECTED'
};

export const REJECTION_REASONS = {
  OUTSIDE_RADIUS: 'OUTSIDE_RADIUS',
  EXPIRED_WINDOW: 'EXPIRED_WINDOW',
  BEFORE_WINDOW: 'BEFORE_WINDOW',
  POOR_ACCURACY: 'POOR_ACCURACY',
  INVALID_COORDINATES: 'INVALID_COORDINATES',
  MEETING_DISABLED: 'MEETING_DISABLED',
  DUPLICATE_CHECKIN: 'DUPLICATE_CHECKIN',
  USER_INACTIVE: 'USER_INACTIVE'
};

export const MEETING_STATUS = {
  UPCOMING: 'UPCOMING',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};
